version: '1'
services:
  tenpo:
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: p05tgr35
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"